version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/Users/yegorgrigoryev/PycharmProjects/bag_shop
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
